---
title: "Gráficos PURECO"
author: "Elizabeth"
date: "`r format(Sys.time(), '%d/%m/%Y')`"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    smooth_scroll: true
    source_code: embed
runtime: shiny
---

```{r, eval = FALSE}
## O eval = FALSE NAO RODA o codigo (DESTE PEDAÇO DE CODIGO)
## Este documento Rmd foi um primeiro um exemplo de ideias de graficos selecionadas para o site principal feito em shiny 
## Nem todos os  graficos que estao no secoes.R estão aqui 
## Aqui temos um documento do tipo flexdashboard que roda de forma iterativa com shiny 
```

```{r setup, include=FALSE}
# o include = FALSE não inclui este codigo, não roda nem mostra 
options(knitr.duplicate.label = 'allow', dplyr.summarise.inform = FALSE)
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

```

```{r, include=FALSE}
# carregando pacotes necessarios
library("plotly")
library("knitr")
library("lubridate")
library("flexdashboard")
library("shiny")
library("shinyWidgets")
library("quantmod")
library("scales")
library("zoo")
```

```{r code = readLines("../Temas.R") , echo = FALSE}
# lendo as informações do codigo Temas.R
```

```{r, results='hide', echo = FALSE}
# lendo e pegando as informações do documento Relatoriotecnicodados.Rmd
knit_child('Relatoriotecnicodados.Rmd')
```

```{r, echo = FALSE}
# modificando o formato de data da planilha de faxinas e disponibilidade para conseguir manipular as datas 
faxinas$Data <-
  as.POSIXct(faxinas$Data, "UTC", format = "%d/%m/%Y")

faxinas$`Dia da Semana` <- wday(faxinas$Data, label = TRUE, abbr = TRUE)

disponibilidade$Data <-  as.POSIXct(disponibilidade$Data, "UTC", format = "%d/%m/%Y")

```

Quantidade de Faxinas por Dias da Semana 
=====================================  

Row
---------------------------------------------------------


### Barplot Quantidade entre os anos 
```{r}
renderPlotly({
# Gráfico de barras de Faxinas por dia da semana  
# dia da semana nao se ordena deixa igual o do site
# para remover a legenda no ggplot show.legend = FALSE  
# no plolty: showlegend = FALSE
  
  g1 <- faxinas %>% 
    filter(Colaboradora != "NA" & `Dia da Semana` != is.na(NA) & `Ocorreu?` == "Sim") %>% 
    mutate(Quantidade = 1) %>%
    group_by(`Dia da Semana`)  %>% 
    summarize(Quantidade = sum(Quantidade)) %>%
    ggplot(aes(x =  `Dia da Semana`,
               y = Quantidade, fill = `Dia da Semana`, 
               text = paste('Dia da Semana:',`Dia da Semana`,
                            '<br>Quantidade:', Quantidade))) +
    geom_bar(stat = "identity", position = "stack") + 
    xlab("Dia da Semana") +
    ylab("Quantidade de Faxinas") + 
    ggtitle("Quantidade de Faxinas por Dia da Semana") +
    scale_fill_viridis_d() +
    tema_geral 

  g1 <- ggplotly(g1, tooltip = "text") %>% 
      layout(showlegend = FALSE)
  
  g1
})
```

### Barplot Quantidade Por ano 

```{r}
renderPlotly({
# Gráfico de barras de Faxinas por dia da semana e por ano
# as.character pois ggplotly nao entende o eixo x como factor-levels
# acrescentei a variavel ano como facets 
  
  g1a <- faxinas %>%
    filter(Colaboradora != "NA" & `Dia da Semana` != is.na(NA) & `Ocorreu?` == "Sim") %>%
    mutate(Quantidade = 1, ano = year(Data)) %>%
    group_by(ano, `Dia da Semana`)  %>%
    summarize(Quantidade = sum(Quantidade)) %>% 
    arrange(ano, Quantidade)  %>%
    ggplot(aes(x = `Dia da Semana`, y = Quantidade, fill = `Dia da Semana`,
                  text = paste('Dia da Semana:', `Dia da Semana`,
                               '<br>Quantidade:', Quantidade))) +
  geom_bar(stat = "identity", position = "stack") +
  facet_grid(~ano, scales = "free_x") + 
  xlab("Dia da Semana") +
  ylab("Quantidade de Faxinas") + 
  ggtitle("Quantidade de Faxinas por Dia da Semana e Ano") +
  scale_fill_viridis_d(aesthetics = "fill") +
  tema_facets 
        
 g1a <- ggplotly(g1a, tooltip = "text") %>%
  layout(showlegend = FALSE)

 g1a
})
```

Row
---------------------------------------------------------

### Boxplot Quantidade entre os anos
```{r}
renderPlotly({
# Gráfico de Faxinas por dia da semana
# valor acumulado ao longo do periodo inserido para análise
# DEPOIS PERCEBI  QUE ESSE GRAFICO ESTAVA ERRADO AO UTILIZAR CUMSUM
# A IDEIA DE BOXPLOT SO SERVE PARA VALORES QUE VARIAM NÃO CONTAGEM COMO AQUI 
  b1 <- faxinas %>% 
    filter(Colaboradora != "NA" & `Ocorreu?` == "Sim") %>% mutate(Quantidade = 1) %>%
    group_by(`Dia da Semana`) %>%
    mutate(Quantidade = cumsum(Quantidade)) %>%
    ggplot(aes(x = `Dia da Semana`,
               y = Quantidade, fill = `Dia da Semana`)) +
    geom_boxplot() + 
    xlab("Dia da Semana") +
    ylab("Quantidade de Faxinas") + 
    ggtitle("Quantidade de Faxinas por Dia da Semana") +
    scale_fill_viridis_d() +
    tema_geral 

 b1 <- ggplotly(b1, tooltip = c("x","y"))  %>%
    layout(showlegend = FALSE)
  
 b1
})  
```

### Boxplot Quantidade Por ano 

```{r}
# Gráfico de Faxinas por dia da semana e por ano 
# valor acumulado ao longo do periodo inserido para análise
# DEPOIS PERCEBI  QUE ESSE GRAFICO ESTAVA ERRADO AO UTILIZAR CUMSUM
# A IDEIA DE BOXPLOT SO SERVE PARA VALORES QUE VARIAM NÃO CONTAGEM COMO AQUI 

renderPlotly({

  b1a <- faxinas %>% 
    filter(Colaboradora != "NA" & `Ocorreu?` == "Sim") %>%
    mutate(Quantidade = 1, ano = year(Data)) %>%
    group_by(ano,`Dia da Semana`) %>%
    summarize(Quantidade = cumsum(Quantidade)) %>%
    arrange(ano, Quantidade) %>%
    ggplot(aes(x = `Dia da Semana`,
              y = Quantidade, fill = `Dia da Semana`)) +
    geom_boxplot() + 
    facet_grid(~ano, scales = "free_x") +
    xlab("Dia da Semana") +
    ylab("Quantidade de Faxinas") + 
    ggtitle("Quantidade de Faxinas por Dia da Semana e Ano") +
    scale_fill_viridis_d(aesthetics = "fill") +
    tema_facets 

  b1a <- ggplotly(b1a, tooltip = c("x","y"))  %>%
      layout(showlegend = FALSE)

  b1a

})
```

### Por Tipo 

```{r}
renderPlotly({
  
# Gráfico de Faxinas por dia Tipo e dia da semana entre os anos 
# valor acumulado ao longo do periodo inserido para análise
  
  g2 <- faxinas %>% 
    filter(Tipo != "NA" & `Ocorreu?` == "Sim" & `Dia da Semana` != is.na(NA)) %>%
    mutate(Quantidade = 1) %>% 
    group_by(Tipo, `Dia da Semana`) %>% 
    summarize(Quantidade = sum(Quantidade)) %>% 
    arrange(Tipo, Quantidade)  %>%
    ggplot(aes(x = `Dia da Semana`, y = Quantidade, fill = `Dia da Semana`,
             text = paste('Dia da Semana:', `Dia da Semana`,
                               '<br>Quantidade:', Quantidade))) +
    geom_bar(stat = "identity", position = "stack") +
    facet_wrap(~Tipo, scales = "free_x") + 
    xlab("Dia da Semana") +
    ylab("Quantidade de Faxinas") + 
    ggtitle("Quantidade de Faxinas por Tipo de faxina e Dia da Semana") +
    scale_fill_viridis_d(aesthetics = "fill") +
    tema_facets 

  g2 <- ggplotly(g2, tooltip ="text") %>%
    layout(showlegend = FALSE)
        
  g2
})        
```

Quantidade de faxinas por Colaboradora
=====================================  

Row{.tabset}
-------------------------------------


### Quantidade de faxinas totais por Colaboradora

```{r}
renderPlotly({
  
  m1 <- faxinas %>% 
    filter(Colaboradora != "NA" & Colaboradora != "Maria" & `Ocorreu?` == "Sim") %>%
    mutate(Quantidade = 1) %>%
    group_by(Colaboradora)  %>% 
    summarize(Quantidade = sum(Quantidade)) %>%
    ggplot(aes(x =  reorder(Colaboradora, -Quantidade,),
               y = Quantidade, fill = Colaboradora, 
               text = paste('Colaboradora:',
                          reorder(Colaboradora, Quantidade),
                          '<br>Quantidade:', Quantidade))) +
    geom_bar(stat = "identity", position = "stack") + 
    xlab("Colaboradora") +
    ylab("Quantidade de Faxinas") + 
    ggtitle("Quantidade de Faxinas por Colaboradora")  +
    scale_fill_viridis_d() +
    tema_geral 
  
  m1 <- ggplotly(m1, tooltip = "text") %>%
    layout(showlegend = FALSE)
        
  m1
})
```


### Quantidade de faxinas por Colaboradora e ano 
```{r}
faxinas_m1a <- faxinas %>% 
  filter(Colaboradora != "NA" & Colaboradora != "Maria" & 
           `Ocorreu?` == "Sim" & `Dia da Semana` != is.na(NA)) %>%
  mutate(Quantidade = 1, ano = year(Data)) %>% 
  group_by(ano, Colaboradora) %>% 
  summarize(Quantidade = sum(Quantidade)) %>% 
  arrange(ano, Quantidade)  %>%
  mutate(Colaboradora_ano = reorder(factor(paste(Colaboradora, ano)), -Quantidade)) 

```

```{r}
renderPlotly({

m1a <- ggplot(faxinas_m1a , 
              aes(x = Colaboradora_ano , y = Quantidade, fill = Colaboradora, 
             text = paste('Colaboradora:', Colaboradora,
                          '<br>Quantidade:', Quantidade))) +
  geom_bar(stat = "identity", position = "dodge") + 
  facet_grid(~ano, scales = "free_x") +
  xlab("Colaboradora") +
  ylab("Quantidade de faxinas") +
  ggtitle("Quantidade de Faxinas por Colaboradora e ano") +
  scale_x_discrete(labels = as.character(faxinas_m1a$Colaboradora), 
                   breaks = faxinas_m1a$Colaboradora_ano) +
  scale_fill_viridis_d(aesthetics = "fill") +
  tema_facets
        
  m1a <- ggplotly(m1a, tooltip = "text") %>%
    layout(showlegend = FALSE)
        
  m1a
})
```

### Quantidade de faxinas por Colaboradora e Dia da Semana

```{r}
renderPlotly({
        
  m2 <- faxinas %>% 
    filter(Colaboradora != "NA" & Colaboradora != "Maria" &
           `Ocorreu?` == "Sim" & `Dia da Semana` != is.na(NA)) %>%
    mutate(Quantidade = 1) %>% 
    group_by(Colaboradora, `Dia da Semana`)  %>%
    summarize(Quantidade = sum(Quantidade)) %>% 
    arrange(Colaboradora, Quantidade) %>% 
    ggplot(aes(x = `Dia da Semana`, y = Quantidade, fill = `Dia da Semana`,
                 text  = paste('Dia da Semana:', `Dia da Semana`,
                               '<br>Quantidade:', Quantidade))) +
    geom_bar(stat = "identity", position = "dodge") +
    facet_grid(~Colaboradora, scales = "free_x") +
    xlab("Dia da Semana") +
    ylab("Quantidade de faxinas") +
    ggtitle("Quantidade de Faxinas por Colaboradora e Dia da Semana") +
    scale_fill_viridis_d(aesthetics = "fill") +
    tema_facets 
        
  m2 <- ggplotly(m2, tooltip = "text") %>%
    layout(showlegend = FALSE)
    
  m2
})
```

### Calendário

```{r}

## PRIMEIRA TENTATIVA DE FAZER UM GRAFICO DE CALENDARIO ## 

### MUDAR ESSE 
renderPlotly({
# library('plyr')
disponibilidade2 <- fortify.zoo(disponibilidade)

disponibilidade2 <- disponibilidade2 %>% 
  filter(Disponibilidade != "NA") %>%
  mutate(ano = year(Data), mes = month(Data, label = TRUE),
         dia= day(Data),
         Semana = as.numeric(format(Data, "%W")),
         `Dia da Semana` = wday(Data, label=TRUE, abbr = FALSE,
                                getOption("lubridate.week.start", 7))) 
  
  
# disponibilidade2 <- ddply(disponibilidade2,
#                           .(mesano),transform,semanadomes=1+Semana-min(Semana))  

  # d1 <- ggplot(disponibilidade2, aes(x = Semana, y = `Dia da Semana`)) + 
  # geom_tile(aes(fill = Colaboradora)) + 
  # facet_grid(ano~mes, scales="free", space="free") + 
  # ggtitle("Calendário de Disponibilidade") +
  # theme(axis.title.x = element_blank(),
  #       axis.text.x = element_blank(),
  #       panel.background = element_blank(),
  #       strip.background = element_rect(colour = "black", fill = "#99CCFF"))
  # 
  # d1 <- ggplotly(d1)
  #       
  # d1

 ggplotly(disponibilidade %>% filter(Disponibilidade != "NA", Colaboradora == "Zilza") %>%
    mutate(ano = year(Data), mes = month(Data, label = TRUE),
           dia= day(Data),
           Semana = as.numeric(format(Data, "%W")),
           `Dia da Semana` = wday(Data, label=TRUE, abbr = FALSE,
                                  getOption("lubridate.week.start", 7))) %>% group_by(Semana,ano,mes,`Dia da Semana`,Colaboradora) %>% count(Colaboradora) %>% ggplot(aes(y = Semana, x = `Dia da Semana`)) + 
    geom_tile(aes(fill = Colaboradora)) + 
    facet_grid(ano~mes, scales="free_y")) 

})
```

Proporção  
=====================================  

Inputs {.sidebar}

-----------------------------------------------------------------------

```{r}
faxinas_ano <- faxinas %>% mutate(ano = year(Data))
```

```{r}
pickerInput(
  inputId = "Colaboradora",
  label = "Escolha a Colaboradora :",
  choices = c("Ledinha", "Lourdes", "Marcela", "Vilanir", "Zilza"),
  selected = "Lourdes",
  multiple = TRUE
)

pickerInput(
  inputId = "ano",
  label = "Escolha o Ano:",
  choices = c(2018,2019,2020),
  selected = 2018,
  multiple = TRUE
)
```

Outputs
------------------------------------------------

### Gráfico de faxinas por ano para cada Colaboradora 

```{r}
filtro_Colaboradoraes <- reactive({
  
  faxinas %>% 
    filter(Colaboradora != "Maria" & `Ocorreu?` == "Sim" &
             `Dia da Semana` != is.na(NA)) %>%
    mutate(Quantidade = 1, ano = year(Data)) %>%
    group_by(ano, Colaboradora, `Dia da Semana`)  %>%
    summarize(Quantidade = sum(Quantidade)) %>%
    arrange(ano, Colaboradora, Quantidade) %>%
    filter(Colaboradora %in% input$Colaboradora & ano %in% input$ano) %>% 
    mutate(Prop = round(Quantidade/sum(Quantidade), 2))
  
})

renderPlotly({

# Proporção de faxinas realizadas por Colaboradora 
  m3 <- ggplot(filtro_Colaboradoraes(), 
                  aes(x = `Dia da Semana`,
                      y = Prop, fill = Colaboradora, 
                      text = paste('Dia da Semana:',
                                   `Dia da Semana`, 
                                   '<br>Proporção de faxinas realizadas:',
                                   Prop, 
                                   '<br>Quantidade de faxinas realizadas:',
                                   Quantidade, 
                                   '<br>Colaboradora:', Colaboradora))) +
      geom_bar(stat = "identity", position = "stack") +
      facet_grid(.~ano) +
      coord_flip(expand = TRUE) +
      xlab("Dia da Semana") +
      ylab("Proporção de faxinas realizadas") +
      ggtitle("Proporção de Faxinas por ano e Colaboradora") +
      scale_fill_discrete()+
      tema_facets
  
  m3 <- ggplotly(m3, tooltip = "text") 
  
  m3
})

```

Clientes
=====================================  

Faxinas em geral 
=====================================  

Page with Tabset {.tabset .tabset-fade}
-------------------------------------

```{r}
faxinas2 <- faxinas %>% filter(`Ocorreu?` == "Sim") %>%
          mutate(fax = 1)
        
x <- data.frame(Data = seq.POSIXt(from = min(faxinas2$Data),
                                          to = max(faxinas2$Data),
                                          by = "day"),QTDE = 0)
        
faxinas2 <- full_join(faxinas2, x, by = c("Data"))
faxinas2 <- faxinas2 %>% select(-QTDE)
faxinas2$fax[is.na(faxinas2$fax)] <- 0
        
faxinas2 <- faxinas2  %>% 
  mutate(`Mês` = month(Data, label = TRUE, abbr = TRUE), ano = year(Data)) %>%
  group_by(ano,`Mês`) %>%
  summarize(Quantidade = sum(fax)) %>% 
  mutate(Quantidade = as.integer(Quantidade)) %>%
  select(`Mês`, Quantidade, ano ) 
```

### Separadas por ano com gráfico de barras {data-width=500}

```{r}
renderPlotly({
  
faxinas2_ano2018 <- faxinas2 %>% 
  filter(ano == "2018") %>%
  ggplot(aes(x = reorder(`Mês`, Quantidade), y = Quantidade, fill = `Mês`,
             text = paste('Mês:', reorder(`Mês`, Quantidade),
                          '<br>Quantidade:', Quantidade))) +
  geom_bar(stat = "identity", position = "stack") +
  xlab("Meses-2018") + ylab("Número de Faxinas") +
  ggtitle("Quantidade de faxinas Totais") +
  scale_fill_viridis_d()

faxinas2_ano2019 <- faxinas2 %>% 
  filter(ano == "2019") %>%
  ggplot(aes(x = reorder(`Mês`, Quantidade), y = Quantidade, fill = `Mês`,
             text = paste('Mês:', reorder(`Mês`, Quantidade),
                          '<br>Quantidade:', Quantidade))) +
  geom_bar(stat = "identity", position = "stack") +
  xlab("Meses-2019") + ylab("Número de Faxinas") +
  ggtitle("Quantidade de faxinas totais realizadas") +
  scale_fill_viridis_d()

faxinas2_ano2020 <- faxinas2 %>% 
  filter(ano == "2020") %>%
  ggplot(aes(x = reorder(`Mês`, Quantidade), y = Quantidade, fill = `Mês`,
             text = paste('Mês:', reorder(`Mês`, Quantidade),
                          '<br>Quantidade:', Quantidade))) +
  geom_bar(stat = "identity", position = "stack") +
  xlab("Meses-2020") + ylab("Número de Faxinas") +
  ggtitle("Quantidade de faxinas totais realizadas") +
  scale_fill_viridis_d()

faxinas2_ano2018 <- faxinas2_ano2018  + tema_faxinas2
faxinas2_ano2019 <- faxinas2_ano2019  + tema_faxinas2
faxinas2_ano2020 <- faxinas2_ano2020  + tema_faxinas2

faxinas2_ano2018 <- ggplotly(faxinas2_ano2018, tooltip = "text")
faxinas2_ano2019 <- ggplotly(faxinas2_ano2019, tooltip = "text")
faxinas2_ano2020 <- ggplotly(faxinas2_ano2020, tooltip = "text")

subplot(faxinas2_ano2018, faxinas2_ano2019, faxinas2_ano2020, 
        titleX = TRUE)

})

```

### Usando facet grid com gráfico de linhas {data-width=500}

```{r}
renderPlotly({
  
f2 <- faxinas2 %>% 
  ggplot(aes(x=`Mês`, y = Quantidade, group = 1)) +
  geom_line(col = "blue") +
  facet_grid(~ano) +
  ylab("Quantidades de faxinas por mês") + 
  ggtitle("Quantidade de Faxinas Totais por Ano") +
  tema_facets 

  f2 <- ggplotly(f2, tooltip = c("x", "y"))
  
  f2
})
```

Row{.tabset}
------------------------------------------------------------

### Feedback Faxinas

```{r}
renderPlotly({
fe1 <- faxinas %>% 
  filter(`Ocorreu?` != "NA" & `Ocorreu?`=="Sim" & 
               `Nota feedback cliente` != "NA" & Colaboradora != "NA") %>% 
  mutate(ano = year(Data)) %>% 
  ggplot(aes( x=`Nota feedback cliente`, fill = Colaboradora,                                         group = interaction(`Nota feedback cliente`, Colaboradora))) +
  geom_bar() + 
  facet_grid(~ano) +
  ylab("Quantidade de feedbacks") +
  ggtitle("Nota de feedback dos clientes por Colaboradora e Ano") +
  tema_facets + 
  theme(axis.text.x = element_text(size = 8)) 
  
  fe1 <- ggplotly(fe1, tooltip = c("x", "y"))

  fe1
})
```

### Informação sobre as faxinas que não ocorreram 

```{r}
renderPlotly({

# tenho apenas uma informação em 2020
  
f1 <- faxinas %>% 
  mutate(ano = year(Data), Quantidade = 1) %>%
  filter(`Ocorreu?`== "Não" & Remarcou != "NA" & Colaboradora != "NA") %>% 
  group_by(Remarcou, Colaboradora, ano) %>%                         
  summarize(Quantidade = sum(Quantidade)) %>% 
  ggplot(aes(x=Remarcou, y = Quantidade, fill = Colaboradora)) + 
  geom_bar(stat = "identity", position = "stack") + 
  facet_grid(~ano) +
  ylab("Número de faxinas que não ocorreram") +
  ggtitle("Número de faxinas remarcadas por Ano e por Colaboradora") +
  scale_y_continuous(breaks = c(0.0,2,4,6,8,10,12)) +
  tema_facets 

  f1 <- ggplotly(f1, tooltip = c("x","y")) 
  
  # layout(legend = list(orientation = "h", x = 0.3, y = -0.1))
  
  f1  
})
```


```{r, eval = FALSE} 
## Ideias de Analises (DEZEMBRO 2020)

#encaixar na secao de mulheres se der

#quanto cada mulher ganhou no ano de 2019 por ex
View(faxinas %>%  filter(ano %in% 2019,
                         Mulher != "NA", `Ocorreu?` == "Sim") %>% 
       group_by(ano, Mulher) %>% summarise(Valor = sum(Valor))) 

# quanto cada mulher ganhou no mes e por ano
View(faxinas %>%  filter(ano %in% 2019,
                         Mulher != "NA", `Ocorreu?` == "Sim") %>% 
       group_by(ano, mes,Mulher) %>% summarise(Valor = sum(Valor))) 



##encaixar em geral 
#quanto o pureco arrecadou por dia da semana/mes/ano

#semana
View(faxinas %>%  filter(ano %in% 2019,
Mulher != "NA", `Ocorreu?` == "Sim") %>% 
  group_by(ano, Semana) %>% summarise(Valor = sum(Valor))) 

#mes
View(faxinas %>%  filter(ano %in% 2019,
Mulher != "NA", `Ocorreu?` == "Sim") %>% 
  group_by(ano, mes) %>% summarise(Valor = sum(Valor))) 

#ano
View(faxinas %>%  filter(ano %in% c(2018,2019,2020) %>%
Mulher != "NA", `Ocorreu?` == "Sim") %>% 
  group_by(ano) %>% summarise(Valor = sum(Valor))) 
```

